SimplifiedMortgageRefi/Areas/Identity/Pages/Account/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SimplifiedMortgageRefi.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ILogger<LogoutModel> _logger;

        public LogoutModel(SignInManager<IdentityUser> signInManager, ILogger<LogoutModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost(string returnUrl = null)
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            if (returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                return RedirectToPage();
            }
        }
    }
}

SimplifiedMortgageRefi/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SimplifiedMortgageRefi.Data;
using SimplifiedMortgageRefi.Models;
using SimplifiedMortgageRefi.ViewModels;

namespace SimplifiedMortgageRefi.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {

            ContactCustomerViewModel viewModel = new ContactCustomerViewModel();
            
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var customer = _context.Customers.Where(c => c.IdentityUserId == userId).FirstOrDefault();
            viewModel.Customer = customer;
            if(customer == null)
            {
                return RedirectToAction(nameof(Create));
            }
            var application = await _context.Applications_Customers.Where(c => c.CustomerId == customer.Id).Select(d => d.Application).FirstOrDefaultAsync();
            var loanProfiles = await _context.LoanProfiles.Where(c => c.ApplicationId == application.Id).ToListAsync();
            var propertyInDb = await _context.Customers_Properties.Where(p => p.CustomerId == customer.Id).Select(q => q.Property).FirstOrDefaultAsync();
            if(propertyInDb.Rate == 0)
            {
                return RedirectToAction(nameof(EditCurrentMortgage));
            }
            var liabilities = await _context.Liabilities.Where(l => l.ApplicationId == application.Id).ToListAsync();

            viewModel.Property = propertyInDb;
            viewModel.Application = application;
            viewModel.LoanProfiles = loanProfiles;
            viewModel.Liabilities = liabilities;

            double liabilityTotal = 0;
            foreach(var item in liabilities)
            {
                liabilityTotal += item.Payment;
            }
            double monthlyExpenses = propertyInDb.MonthlyPayment + propertyInDb.MonthlyHOIPremium + propertyInDb.MonthlyPropertyTax + liabilityTotal;
            propertyInDb.MonthlyExpenses = monthlyExpenses;
            propertyInDb.DebtToIncome = Math.Round((monthlyExpenses / customer.MonthlyIncome) * 100, 2);
            _context.SaveChanges();

            return View(viewModel);
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .Include(c => c.IdentityUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {

            CreateCustomerViewModel createCustomerViewModel = new CreateCustomerViewModel();

            ViewData["States"] = new SelectList(_context.States, "Id", "Name", "Select State");
            ViewData["Purposes"] = new SelectList(_context.Purposes, "Id", "Name", "Select");
            ViewData["PropertyTypes"] = new SelectList(_context.PropertyTypes, "Id", "Name");
            ViewData["OccupancyTypes"] = new SelectList(_context.OccupancyTypes, "Id", "Name");
            return View(createCustomerViewModel);
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("FirstName,LastName,CreditScore,MonthlyIncome")] Customer customer,
            [Bind("AssessedValue")] Property property,
            [Bind("Street, City, StateId, ZipCode")] Address address,
            [Bind("PurposeId")] LoanProfile loanProfile)
        {
            if (ModelState.IsValid)
            {

                //Get customer role
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                customer.IdentityUserId = userId;

                _context.Add(customer); //Add customer to DB

                _context.Add(address); //Add address to DB
                _context.SaveChanges(); //Customer and Address get PK

                property.AddressId = address.Id; //Add AddressId as FK to property
                property.OccupancyTypeId = 1;
                property.PropertyTypeId = 1;
                _context.Add(property); // 
                _context.SaveChanges(); //give Property a PK

                Customers_Properties customers_Properties = new Customers_Properties();
                customers_Properties.CustomerId = customer.Id;
                customers_Properties.PropertyId = property.Id;
                _context.Add(customers_Properties);
                _context.SaveChanges(); //Add FKs to Customers_Properties junction

                Application application = new Application();
                application.ApplicationStartDate = DateTime.Now; //Timestamp application
                application.PropertyId = property.Id;
                _context.Add(application); //Add application to DB
                _context.SaveChanges(); //give application PK

                Applications_Customers applications_Customers = new Applications_Customers();
                applications_Customers.CustomerId = customer.Id;  //for Junction table
                applications_Customers.ApplicationId = application.Id; //for Junction table
                _context.Add(applications_Customers);


                loanProfile.Originator = "Customer";
                loanProfile.ApplicationId = application.Id;
                if (loanProfile.PurposeId == 2)
                {
                    loanProfile.IsCashOut = true;
                }
                _context.Add(loanProfile);

                _context.SaveChanges();


                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(EditCurrentMortgage));
            }
            return View(customer);
        }

 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateLoanProfile([Bind("Id")] Application application,
    [Bind("Term,Rate,LoanAmount,ClosingCost")] LoanProfile loanProfile)
        {
           
            if (ModelState.IsValid)
            {
                var purposeId = _context.LoanProfiles.Where(l => l.ApplicationId == application.Id).Select(p => p.PurposeId).FirstOrDefault();
                loanProfile.Originator = "Customer";
                loanProfile.ApplicationId = application.Id;
                loanProfile.PurposeId = purposeId;


                _context.Add(loanProfile);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        public async Task<IActionResult> EditCurrentMortgage()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var customer = await _context.Customers.Where(c => c.IdentityUserId == userId)
                .FirstOrDefaultAsync();

            if (customer == null)
            {
                return NotFound();
            }

            IndexCustomerViewModel indexCustomerViewModel = new IndexCustomerViewModel()
            {
                Customer = customer
            };

            return View(indexCustomerViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCurrentMortgage(
        [Bind("OriginalMortgageBalance, Rate, Term, MonthlyPropertyTax, MonthlyHOIPremium, Id, OriginationDate")] Property property)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var customer = _context.Customers.Where(c => c.IdentityUserId == userId).FirstOrDefault();
            if (ModelState.IsValid)
            {
                //Get customer
                var propertyInDb = _context.Customers_Properties.Where(p => p.CustomerId == customer.Id).Select(q => q.Property).FirstOrDefault();
                propertyInDb.MortgageBalance = property.MortgageBalance;
                propertyInDb.OriginalMortgageBalance = property.OriginalMortgageBalance;
                propertyInDb.Rate = property.Rate;
                propertyInDb.Term = property.Term;
                propertyInDb.MonthlyPropertyTax = property.MonthlyPropertyTax;
                propertyInDb.MonthlyHOIPremium = property.MonthlyHOIPremium;
                propertyInDb.OriginationDate = property.OriginationDate;

                double monthlyRate = property.Rate / 100 / 12;
                int monthsPaid = 12 * Math.Abs(DateTime.Now.Year - property.OriginationDate.Year) + Math.Abs(DateTime.Now.Month - property.OriginationDate.Month);
                int monthsLeft = (property.Term * 12) - monthsPaid;
                int totalPayments = property.Term * 12;
                var x = Math.Pow(1 + monthlyRate, totalPayments);
                double monthlyPayment = (property.OriginalMortgageBalance * x * monthlyRate) / (x - 1);
                propertyInDb.MonthlyPayment = Math.Round(monthlyPayment, 2);

                var currentBalance = monthlyPayment * (1 - Math.Pow(1 + monthlyRate, -(monthsLeft))) / monthlyRate;
                propertyInDb.MortgageBalance = Math.Round(currentBalance, 2);
                double loanToValue = Math.Round((currentBalance / propertyInDb.AssessedValue) * 100, 2);

SimplifiedMortgageRefi/Controllers/LendersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SimplifiedMortgageRefi.Data;
using SimplifiedMortgageRefi.Models;

namespace SimplifiedMortgageRefi.Controllers
{
    public class LendersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LendersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            //var applicationDbContext = _context.Applications.Include(c => c.Property);
            var applicationDbContext = _context.Applications_Customers
                .Include(a => a.Application.Property)
                .Include(a => a.Application.Contacts)
                .Include(c => c.Customer);
            int i = 0;
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Lenders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lender = await _context.Customers
                .Include(l => l.IdentityUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lender == null)
            {
                return NotFound();
            }

            return View(lender);
        }

        public async Task<IActionResult> CreateContact(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lender = await _context.Applications
                .Include(l => l.Customers)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lender == null)
            {
                return NotFound();
            }

            return View(lender);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> CreateContact([Bind("Id,Result")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contact);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(contact);
        }

        // GET: Lenders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Lenders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,IdentityUserId")] Lender lender)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                lender.IdentityUserId = userId;
                _context.Add(lender);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(lender);
        }

        // GET: Lenders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lender = await _context.Customers.FindAsync(id);
            if (lender == null)
            {
                return NotFound();
            }
            return View(lender);
        }

        // POST: Lenders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,IdentityUserId")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LenderExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Lenders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lender = await _context.Lenders
                .Include(l => l.IdentityUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lender == null)
            {
                return NotFound();
            }

            return View(lender);
        }

        // POST: Lenders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lender = await _context.Lenders.FindAsync(id);
            _context.Lenders.Remove(lender);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LenderExists(int id)
        {
            return _context.Lenders.Any(e => e.Id == id);
        }
    }
}

SimplifiedMortgageRefi/Views/Shared/CreateLiabilities.cshtml
@model SimplifiedMortgageRefi.ViewModels.ContactCustomerViewModel

@{
    ViewData["Title"] = "Liabilities";
    Layout = "~/Views/Shared/_CustomerDashboard.cshtml";
}

<h1>Manage My Debts</h1>

<h4>Add your debt list below</h4>
<hr />
<button id="link-button">Link Account</button>

<div class="row mr-4 ml-4">


    <div class="col-md-4 d-inline-flex float-left">
        <form asp-action="CreateLiabilities">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Application.Id" />
            <div class="form-group">
                <label asp-for="Liability.LenderName" class="control-label"></label>
                <input asp-for="Liability.LenderName" class="form-control" />
                <span asp-validation-for="Liability.LenderName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Liability.Balance" class="control-label"></label>
                <input asp-for="Liability.Balance" class="form-control" />
                <span asp-validation-for="Liability.Balance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Monthly Payment</label>
                <input asp-for="Liability.Payment" class="form-control" />
                <span asp-validation-for="Liability.Payment" class="text-danger"></span>
            </div>
            <div class="form-group form-check">

                <input class="form-check-input" asp-for="Liability.IsConsolidated" />
                <label class="form-check-label">I am planning to consolidate this debt into the new mortgage</label>

            </div>
            <div class="form-group">
                <label class="form-check-label">Type of Debt</label>
                 <select asp-for="Liability.LiabilityTypeId" class="form-control form-control-user" asp-items=ViewBag.LiabilityTypes placeholder="Select"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>

    <div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Lender Name
                    </th>
                    <th>
                        Balance
                    </th>
                    <th>
                        Payment
                    </th>
                    <th>
                        Type of Debt
                    </th>
                </tr>
            </thead>
            <tbody>

                @if (Model.Application.Liabilities != null)
                {

                    foreach (var item in Model.Liabilities)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.LenderName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Balance)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Payment)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LiabilityType.Name)
                            </td>
                            <td>

                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>


    </div>
</div>

<div class="row mr-4 ml-4">

    <div>
        <a asp-action="Index">Back to My Dashboard</a>
    </div>

</div>

SimplifiedMortgageRefi/Views/Shared/Logout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

    <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
        <button type="submit" class="dropdown-item">Logout</button>

    </form>

SimplifiedMortgageRefi/Views/Shared/View.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>
</head>
<body>
</body>
</html>

SimplifiedMortgageRefi/Views/Shared/_CustomerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimplifyMyRefi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~theme/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/jQueryMaskPlugin/jquery.mask.js" type="text/javascript"></script>
    <script src="~/jQueryMaskPlugin/jquery.maskMoney.js" type="text/javascript"></script>
    <script src="~/js/site.js" type="text/javascript"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Customers" asp-action="Index">SimplifyMyRefi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @*<div class="container">*@
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    @*</div>*@

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SimplifyMyRefi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>



    <script src="~/js/site.js" asp-append-version="true"></script>


    @RenderSection("Scripts", required: false)

</body>
</html>

SimplifiedMortgageRefi/Views/Shared/_LenderLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimplifyMyRefi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />
  

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Employees" asp-action="Index">SimplifyMyRefi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lenders" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 pt-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SimplifyMyRefi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~theme/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>